version: "3"
services:
  mysql:
    image: library/mysql:5.7
    container_name: mysql
    ports:
      - 13306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: financial_ledger
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h 127.0.0.1 -u root --password=password",
        ]
      interval: 10s
      timeout: 2s
      retries: 100
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /var/lib/mysql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - 8000:8000
    volumes:
      - .:/api
    stdin_open: true
    tty: true
    depends_on:
      mysql:
        condition: service_healthy
