# Generated by Django 4.1.4 on 2022-12-30 02:21

import apps.util.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.FloatField(default=apps.util.models.timestamp_now),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.FloatField(default=apps.util.models.timestamp_now),
        ),
    ]
